"<!DOCTYPE html>"
"<html lang=\"en\"><head>"
"<meta charset=\"utf-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
"<title>WiFi Config</title>"
"</head><body><h1>WiFi Config</h1>"
"<h2 style=\"color:red;\">%s</h2>"
"<p><form action=\"/\" method=\"POST\">"
"<!-- -->"
"<div>WiFi SSID<input type=\"text\" name=\""KEY_WIFI_SSID"\" value=\"%s\" /></div>"
"<div>WiFi Password<input type=\"password\" name=\""KEY_WIFI_PSWD"\" value=\"%s\" /></div>"
"<div>NTP Host Name<input type=\"text\" name=\""KEY_NTPD_HOST"\" value=\"%s\" /></div>"
"<!-- -->"
"<hr noshade>"
"<div><button type=\"submit\">Update & Reload</button></div>"
"<div><button type=\"submit\" name=\"reboot\" value=\"yes\">Update & Reboot</button></div>"
"</form><p/></body></html>";